project_name: protoc-gen-rails
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    dir: protoc-gen-rails
    goos:
      - linux
      - darwin
    binary: protoc-gen-rails
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: flipp-oss
    name: grpc-rest

archives:
  - id: protoc-gen-rails
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
